version: "3.5"

networks:
  stellar-testnet:
    name: ${TESTNET_NAME:-stellar_testnet}

services:
  stellar-horizon:
    image: stellar/horizon:latest
    container_name: stellar-horizon
    restart: on-failure
    ports:
    - 8000:8000
    environment:
      - DATABASE_URL=postgres://postgres:unic_iff@stellar-core-postgres/stellar_horizon_db?sslmode=disable
      - STELLAR_CORE_DATABASE_URL=postgres://postgres:unic_iff@stellar-core-postgres/stellar-genesis?sslmode=disable
      - STELLAR_CORE_URL=http://stellar-genesis:11626
      - HISTORY_ARCHIVE_URLS=http://stellar-archive-publisher:80
      - NETWORK_PASSPHRASE=Standalone UNIC_IFF Network ; 2022          
      - INGEST=true
      - STELLAR_CORE_BINARY_PATH=/usr/bin/stellar-core
      - CAPTIVE_CORE_CONFIG_PATH=/etc/default/stellar-captive-core.toml
      - ENABLE_CAPTIVE_CORE_INGESTION=false
    volumes:
      - /home/mtouloupos/blockchain-benchmarking-framework/templates:/etc/default
    networks:
      - stellar-testnet
  stellar-validator0:
    image: stellar/stellar-core:latest
    container_name: stellar-validator-0
    volumes:
      - /home/mtouloupos/blockchain-benchmarking-framework/configs/stellar-validator-0:/etc/stellar/ 
    networks:
      - stellar-testnet
    command: run
    ports:
      - 11635
      - 11636
    expose:
      - 11635
      - 11636
  stellar-validator1:
    image: stellar/stellar-core:latest
    container_name: stellar-validator-1
    volumes:
      - /home/mtouloupos/blockchain-benchmarking-framework/configs/stellar-validator-1:/etc/stellar/ 
    networks:
      - stellar-testnet
    command: run
    ports:
      - 11635
      - 11636
    expose:
      - 11635
      - 11636
