FAILURE_SAFETY=0
UNSAFE_QUORUM=true


[[HOME_DOMAINS]]
HOME_DOMAIN="stellarprivnet.unic..ac.cy"
QUALITY="MEDIUM"

[[VALIDATORS]]
NAME="stellar-genesis"
HOME_DOMAIN="stellarprivnet.unic.ac.cy"
PUBLIC_KEY="GAZGG462IQ7YGGVRZKDGKYAOD2DKJHW7VOXZYHUXHI7SAR5NDT7NOWRK"
ADDRESS="http://stellar-genesis:11626"
HISTORY="curl -sf http://stellar-archive-publisher:80/{0} -o {1}"


[[VALIDATORS]]
NAME="stellar-validator-0"
HOME_DOMAIN="stellarprivnet.unic.ac.cy"
PUBLIC_KEY="GA33Z5NQBUDPIGZPDQU6ZBZIQAD3IQ5HU45ZLGESGABI5YQ7FXIHZNUT"
ADDRESS="http://stellar-validator-0:11626"


[[VALIDATORS]]
NAME="stellar-validator-1"
HOME_DOMAIN="stellarprivnet.unic.ac.cy"
PUBLIC_KEY="GAYQJAX2GNWNPES2UJJHJK4RLIWMYCQSF6TNWXL74J572Q7Z6LPPPSQ4"
ADDRESS="http://stellar-validator-1:11626"


